name: Security report workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
    paths:
    - docker-image/**
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/*/}"
      id: extract_branch
      
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push security-report docker image
      run: |
        unameOut="${{ steps.extract_branch.outputs.branch }}"
        case "${unameOut}" in
            main)     tag=stable;;
            develop)  tag=latest;;
            v*)       tag=${unameOut};;
        esac
        make -C docker-image deploy-security-report DOCKER_TAG=${tag}
